/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InvitesRouteImport } from './routes/invites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardStreaksRouteImport } from './routes/dashboard/streaks'
import { Route as DashboardInvitationsRouteImport } from './routes/dashboard/invitations'
import { Route as DashboardInteractionsRouteImport } from './routes/dashboard/interactions'
import { Route as DashboardStreakIdRouteImport } from './routes/dashboard/$streakId'

const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesRoute = InvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStreaksRoute = DashboardStreaksRouteImport.update({
  id: '/streaks',
  path: '/streaks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInteractionsRoute = DashboardInteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStreakIdRoute = DashboardStreakIdRouteImport.update({
  id: '/$streakId',
  path: '/$streakId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/invites': typeof InvitesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/sponsor': typeof SponsorRoute
  '/dashboard/$streakId': typeof DashboardStreakIdRoute
  '/dashboard/interactions': typeof DashboardInteractionsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/streaks': typeof DashboardStreaksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invites': typeof InvitesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/sponsor': typeof SponsorRoute
  '/dashboard/$streakId': typeof DashboardStreakIdRoute
  '/dashboard/interactions': typeof DashboardInteractionsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/streaks': typeof DashboardStreaksRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/invites': typeof InvitesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/sponsor': typeof SponsorRoute
  '/dashboard/$streakId': typeof DashboardStreakIdRoute
  '/dashboard/interactions': typeof DashboardInteractionsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/streaks': typeof DashboardStreaksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/invites'
    | '/leaderboard'
    | '/login'
    | '/sponsor'
    | '/dashboard/$streakId'
    | '/dashboard/interactions'
    | '/dashboard/invitations'
    | '/dashboard/streaks'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invites'
    | '/leaderboard'
    | '/login'
    | '/sponsor'
    | '/dashboard/$streakId'
    | '/dashboard/interactions'
    | '/dashboard/invitations'
    | '/dashboard/streaks'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/invites'
    | '/leaderboard'
    | '/login'
    | '/sponsor'
    | '/dashboard/$streakId'
    | '/dashboard/interactions'
    | '/dashboard/invitations'
    | '/dashboard/streaks'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InvitesRoute: typeof InvitesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  SponsorRoute: typeof SponsorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites': {
      id: '/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof InvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/streaks': {
      id: '/dashboard/streaks'
      path: '/streaks'
      fullPath: '/dashboard/streaks'
      preLoaderRoute: typeof DashboardStreaksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invitations': {
      id: '/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/interactions': {
      id: '/dashboard/interactions'
      path: '/interactions'
      fullPath: '/dashboard/interactions'
      preLoaderRoute: typeof DashboardInteractionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$streakId': {
      id: '/dashboard/$streakId'
      path: '/$streakId'
      fullPath: '/dashboard/$streakId'
      preLoaderRoute: typeof DashboardStreakIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardStreakIdRoute: typeof DashboardStreakIdRoute
  DashboardInteractionsRoute: typeof DashboardInteractionsRoute
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardStreaksRoute: typeof DashboardStreaksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardStreakIdRoute: DashboardStreakIdRoute,
  DashboardInteractionsRoute: DashboardInteractionsRoute,
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardStreaksRoute: DashboardStreaksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InvitesRoute: InvitesRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  SponsorRoute: SponsorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
